// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/gin_users/gin_users.proto

package gin_users_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//数据库结构
type GinUsersSchema struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Fullname             string   `protobuf:"bytes,3,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Mobile               string   `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	CreateTime           string   `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GinUsersSchema) Reset()         { *m = GinUsersSchema{} }
func (m *GinUsersSchema) String() string { return proto.CompactTextString(m) }
func (*GinUsersSchema) ProtoMessage()    {}
func (*GinUsersSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_87dfd33193118d48, []int{0}
}

func (m *GinUsersSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GinUsersSchema.Unmarshal(m, b)
}
func (m *GinUsersSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GinUsersSchema.Marshal(b, m, deterministic)
}
func (m *GinUsersSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GinUsersSchema.Merge(m, src)
}
func (m *GinUsersSchema) XXX_Size() int {
	return xxx_messageInfo_GinUsersSchema.Size(m)
}
func (m *GinUsersSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_GinUsersSchema.DiscardUnknown(m)
}

var xxx_messageInfo_GinUsersSchema proto.InternalMessageInfo

func (m *GinUsersSchema) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GinUsersSchema) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GinUsersSchema) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *GinUsersSchema) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *GinUsersSchema) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *GinUsersSchema) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GinUsersSchema) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *GinUsersSchema) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

//更新结构
type UpdateSchema struct {
	Conditions           *GinUsersSchema `protobuf:"bytes,1,opt,name=conditions,proto3" json:"conditions,omitempty"`
	Modifies             *GinUsersSchema `protobuf:"bytes,2,opt,name=modifies,proto3" json:"modifies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateSchema) Reset()         { *m = UpdateSchema{} }
func (m *UpdateSchema) String() string { return proto.CompactTextString(m) }
func (*UpdateSchema) ProtoMessage()    {}
func (*UpdateSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_87dfd33193118d48, []int{1}
}

func (m *UpdateSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSchema.Unmarshal(m, b)
}
func (m *UpdateSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSchema.Marshal(b, m, deterministic)
}
func (m *UpdateSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSchema.Merge(m, src)
}
func (m *UpdateSchema) XXX_Size() int {
	return xxx_messageInfo_UpdateSchema.Size(m)
}
func (m *UpdateSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSchema.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSchema proto.InternalMessageInfo

func (m *UpdateSchema) GetConditions() *GinUsersSchema {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func (m *UpdateSchema) GetModifies() *GinUsersSchema {
	if m != nil {
		return m.Modifies
	}
	return nil
}

//查询结构
type QuerySchema struct {
	Conditions           *GinUsersSchema `protobuf:"bytes,1,opt,name=conditions,proto3" json:"conditions,omitempty"`
	PageNum              int32           `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize             int32           `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *QuerySchema) Reset()         { *m = QuerySchema{} }
func (m *QuerySchema) String() string { return proto.CompactTextString(m) }
func (*QuerySchema) ProtoMessage()    {}
func (*QuerySchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_87dfd33193118d48, []int{2}
}

func (m *QuerySchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuerySchema.Unmarshal(m, b)
}
func (m *QuerySchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuerySchema.Marshal(b, m, deterministic)
}
func (m *QuerySchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySchema.Merge(m, src)
}
func (m *QuerySchema) XXX_Size() int {
	return xxx_messageInfo_QuerySchema.Size(m)
}
func (m *QuerySchema) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySchema.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySchema proto.InternalMessageInfo

func (m *QuerySchema) GetConditions() *GinUsersSchema {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func (m *QuerySchema) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *QuerySchema) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

//查询返回对象
type FindOneRes struct {
	Code                 int32           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string          `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *GinUsersSchema `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FindOneRes) Reset()         { *m = FindOneRes{} }
func (m *FindOneRes) String() string { return proto.CompactTextString(m) }
func (*FindOneRes) ProtoMessage()    {}
func (*FindOneRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_87dfd33193118d48, []int{3}
}

func (m *FindOneRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindOneRes.Unmarshal(m, b)
}
func (m *FindOneRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindOneRes.Marshal(b, m, deterministic)
}
func (m *FindOneRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindOneRes.Merge(m, src)
}
func (m *FindOneRes) XXX_Size() int {
	return xxx_messageInfo_FindOneRes.Size(m)
}
func (m *FindOneRes) XXX_DiscardUnknown() {
	xxx_messageInfo_FindOneRes.DiscardUnknown(m)
}

var xxx_messageInfo_FindOneRes proto.InternalMessageInfo

func (m *FindOneRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *FindOneRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *FindOneRes) GetData() *GinUsersSchema {
	if m != nil {
		return m.Data
	}
	return nil
}

//查询返回string
type FindRes struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindRes) Reset()         { *m = FindRes{} }
func (m *FindRes) String() string { return proto.CompactTextString(m) }
func (*FindRes) ProtoMessage()    {}
func (*FindRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_87dfd33193118d48, []int{4}
}

func (m *FindRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRes.Unmarshal(m, b)
}
func (m *FindRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRes.Marshal(b, m, deterministic)
}
func (m *FindRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRes.Merge(m, src)
}
func (m *FindRes) XXX_Size() int {
	return xxx_messageInfo_FindRes.Size(m)
}
func (m *FindRes) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRes.DiscardUnknown(m)
}

var xxx_messageInfo_FindRes proto.InternalMessageInfo

func (m *FindRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *FindRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *FindRes) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*GinUsersSchema)(nil), "gin_users_proto.GinUsersSchema")
	proto.RegisterType((*UpdateSchema)(nil), "gin_users_proto.UpdateSchema")
	proto.RegisterType((*QuerySchema)(nil), "gin_users_proto.QuerySchema")
	proto.RegisterType((*FindOneRes)(nil), "gin_users_proto.FindOneRes")
	proto.RegisterType((*FindRes)(nil), "gin_users_proto.FindRes")
}

func init() {
	proto.RegisterFile("protos/gin_users/gin_users.proto", fileDescriptor_87dfd33193118d48)
}

var fileDescriptor_87dfd33193118d48 = []byte{
	// 432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0xd3, 0xd8, 0x49, 0x26, 0xa8, 0x54, 0x23, 0x84, 0x4c, 0x0a, 0x6a, 0xe4, 0x53, 0x4f,
	0x41, 0x6a, 0x8f, 0x1c, 0x10, 0x54, 0x6a, 0x25, 0x0e, 0x14, 0x5c, 0x7a, 0x8e, 0xb6, 0xd9, 0xa9,
	0x19, 0x29, 0xbb, 0x8e, 0xbc, 0xb6, 0x50, 0xfb, 0x01, 0x9c, 0xf8, 0x12, 0xbe, 0x8b, 0x0f, 0x41,
	0x3b, 0xeb, 0x44, 0x86, 0x80, 0x88, 0x44, 0x6f, 0xfb, 0xe6, 0xbd, 0x99, 0x7d, 0xf3, 0x76, 0x61,
	0xba, 0xaa, 0xca, 0xba, 0x74, 0x2f, 0x0b, 0xb6, 0xf3, 0xc6, 0x51, 0xd5, 0x39, 0xcd, 0x84, 0xc2,
	0xc7, 0x9b, 0xc2, 0x5c, 0x0a, 0xd9, 0x8f, 0x08, 0xf6, 0x2f, 0xd8, 0x5e, 0xfb, 0xd2, 0xd5, 0xe2,
	0x33, 0x19, 0x85, 0xfb, 0xd0, 0x63, 0x9d, 0x46, 0xd3, 0xe8, 0x38, 0xce, 0x7b, 0xac, 0x71, 0x02,
	0x43, 0xdf, 0x61, 0x95, 0xa1, 0xb4, 0x37, 0x8d, 0x8e, 0x47, 0xf9, 0x06, 0x7b, 0xee, 0xb6, 0x59,
	0x2e, 0x85, 0xdb, 0x0b, 0xdc, 0x1a, 0x7b, 0x6e, 0xa5, 0x9c, 0xfb, 0x52, 0x56, 0x3a, 0xed, 0x07,
	0x6e, 0x8d, 0xf1, 0x29, 0x24, 0xa6, 0xbc, 0xe1, 0x25, 0xa5, 0xb1, 0x30, 0x2d, 0xc2, 0x27, 0x10,
	0x93, 0x51, 0xbc, 0x4c, 0x13, 0x29, 0x07, 0x80, 0x47, 0x30, 0x5e, 0x54, 0xa4, 0x6a, 0x9a, 0xd7,
	0x6c, 0x28, 0x1d, 0x08, 0x07, 0xa1, 0xf4, 0x89, 0x0d, 0x79, 0x41, 0xb3, 0xd2, 0x1b, 0xc1, 0x30,
	0x08, 0x42, 0xc9, 0x0b, 0xb2, 0x6f, 0x11, 0x3c, 0xba, 0x16, 0xd8, 0x2e, 0xf9, 0x1a, 0x60, 0x51,
	0x5a, 0xcd, 0x35, 0x97, 0xd6, 0xc9, 0xb2, 0xe3, 0x93, 0xa3, 0xd9, 0x6f, 0xe9, 0xcc, 0x7e, 0x4d,
	0x26, 0xef, 0xb4, 0xe0, 0x2b, 0x18, 0x9a, 0x52, 0xf3, 0x2d, 0x93, 0x93, 0x54, 0x76, 0x68, 0xdf,
	0x34, 0x64, 0x5f, 0x23, 0x18, 0x7f, 0x6c, 0xa8, 0xba, 0x7b, 0x28, 0x37, 0xcf, 0x7c, 0xd6, 0x05,
	0xcd, 0x6d, 0x63, 0xc4, 0x4d, 0x9c, 0x0f, 0x3c, 0x7e, 0xdf, 0x18, 0x3c, 0x84, 0x91, 0x50, 0x8e,
	0xef, 0xc3, 0x1b, 0xc5, 0xb9, 0x68, 0xaf, 0xf8, 0x9e, 0xb2, 0x02, 0xe0, 0x9c, 0xad, 0xbe, 0xb4,
	0x94, 0x93, 0x43, 0x84, 0xfe, 0xa2, 0xd4, 0xd4, 0xbe, 0xbd, 0x9c, 0xf1, 0x00, 0xf6, 0x8c, 0x2b,
	0xda, 0x87, 0xf7, 0x47, 0x3c, 0x85, 0xbe, 0x56, 0xb5, 0x92, 0x59, 0x3b, 0xd8, 0x14, 0x71, 0x76,
	0x06, 0x03, 0x7f, 0xd1, 0xee, 0xb7, 0x60, 0xe7, 0x96, 0x51, 0x18, 0x72, 0xf2, 0xbd, 0x07, 0xc3,
	0xf5, 0x74, 0x7c, 0x07, 0x07, 0x7e, 0xe2, 0xdb, 0xbb, 0x0f, 0xaa, 0x60, 0xab, 0x7c, 0x0e, 0xf8,
	0x7c, 0xcb, 0x4c, 0x27, 0xe5, 0x49, 0xba, 0xc5, 0xae, 0x2d, 0x5d, 0x04, 0x77, 0x97, 0x96, 0xf0,
	0x5f, 0xfb, 0x4c, 0x0e, 0xff, 0x38, 0xa5, 0x4d, 0xf0, 0x1c, 0x92, 0x33, 0xf9, 0x96, 0xff, 0x39,
	0xe7, 0x0d, 0x24, 0xe1, 0xbb, 0xe2, 0x8b, 0x2d, 0x59, 0xf7, 0x1f, 0xff, 0x7d, 0xa7, 0x9b, 0x44,
	0xe0, 0xe9, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x19, 0x9c, 0x85, 0xe5, 0x15, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GinUsersClient is the client API for GinUsers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GinUsersClient interface {
	FindByPagination(ctx context.Context, in *QuerySchema, opts ...grpc.CallOption) (*FindRes, error)
	FindOne(ctx context.Context, in *GinUsersSchema, opts ...grpc.CallOption) (*FindOneRes, error)
	Create(ctx context.Context, in *GinUsersSchema, opts ...grpc.CallOption) (*FindOneRes, error)
	Update(ctx context.Context, in *UpdateSchema, opts ...grpc.CallOption) (*FindRes, error)
}

type ginUsersClient struct {
	cc grpc.ClientConnInterface
}

func NewGinUsersClient(cc grpc.ClientConnInterface) GinUsersClient {
	return &ginUsersClient{cc}
}

func (c *ginUsersClient) FindByPagination(ctx context.Context, in *QuerySchema, opts ...grpc.CallOption) (*FindRes, error) {
	out := new(FindRes)
	err := c.cc.Invoke(ctx, "/gin_users_proto.GinUsers/FindByPagination", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ginUsersClient) FindOne(ctx context.Context, in *GinUsersSchema, opts ...grpc.CallOption) (*FindOneRes, error) {
	out := new(FindOneRes)
	err := c.cc.Invoke(ctx, "/gin_users_proto.GinUsers/FindOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ginUsersClient) Create(ctx context.Context, in *GinUsersSchema, opts ...grpc.CallOption) (*FindOneRes, error) {
	out := new(FindOneRes)
	err := c.cc.Invoke(ctx, "/gin_users_proto.GinUsers/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ginUsersClient) Update(ctx context.Context, in *UpdateSchema, opts ...grpc.CallOption) (*FindRes, error) {
	out := new(FindRes)
	err := c.cc.Invoke(ctx, "/gin_users_proto.GinUsers/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GinUsersServer is the server API for GinUsers service.
type GinUsersServer interface {
	FindByPagination(context.Context, *QuerySchema) (*FindRes, error)
	FindOne(context.Context, *GinUsersSchema) (*FindOneRes, error)
	Create(context.Context, *GinUsersSchema) (*FindOneRes, error)
	Update(context.Context, *UpdateSchema) (*FindRes, error)
}

// UnimplementedGinUsersServer can be embedded to have forward compatible implementations.
type UnimplementedGinUsersServer struct {
}

func (*UnimplementedGinUsersServer) FindByPagination(ctx context.Context, req *QuerySchema) (*FindRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByPagination not implemented")
}
func (*UnimplementedGinUsersServer) FindOne(ctx context.Context, req *GinUsersSchema) (*FindOneRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOne not implemented")
}
func (*UnimplementedGinUsersServer) Create(ctx context.Context, req *GinUsersSchema) (*FindOneRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedGinUsersServer) Update(ctx context.Context, req *UpdateSchema) (*FindRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}

func RegisterGinUsersServer(s *grpc.Server, srv GinUsersServer) {
	s.RegisterService(&_GinUsers_serviceDesc, srv)
}

func _GinUsers_FindByPagination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySchema)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GinUsersServer).FindByPagination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gin_users_proto.GinUsers/FindByPagination",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GinUsersServer).FindByPagination(ctx, req.(*QuerySchema))
	}
	return interceptor(ctx, in, info, handler)
}

func _GinUsers_FindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GinUsersSchema)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GinUsersServer).FindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gin_users_proto.GinUsers/FindOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GinUsersServer).FindOne(ctx, req.(*GinUsersSchema))
	}
	return interceptor(ctx, in, info, handler)
}

func _GinUsers_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GinUsersSchema)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GinUsersServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gin_users_proto.GinUsers/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GinUsersServer).Create(ctx, req.(*GinUsersSchema))
	}
	return interceptor(ctx, in, info, handler)
}

func _GinUsers_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSchema)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GinUsersServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gin_users_proto.GinUsers/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GinUsersServer).Update(ctx, req.(*UpdateSchema))
	}
	return interceptor(ctx, in, info, handler)
}

var _GinUsers_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gin_users_proto.GinUsers",
	HandlerType: (*GinUsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindByPagination",
			Handler:    _GinUsers_FindByPagination_Handler,
		},
		{
			MethodName: "FindOne",
			Handler:    _GinUsers_FindOne_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _GinUsers_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _GinUsers_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/gin_users/gin_users.proto",
}
