// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gin_user_fields.proto

package gin_user_fields_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//数据库结构
type GinUserFieldsSchema struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Sexy                 string   `protobuf:"bytes,2,opt,name=sexy,proto3" json:"sexy,omitempty"`
	Birthdy              string   `protobuf:"bytes,3,opt,name=birthdy,proto3" json:"birthdy,omitempty"`
	IdCard               string   `protobuf:"bytes,4,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	TruthName            string   `protobuf:"bytes,5,opt,name=truth_name,json=truthName,proto3" json:"truth_name,omitempty"`
	Created              string   `protobuf:"bytes,6,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string   `protobuf:"bytes,7,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GinUserFieldsSchema) Reset()         { *m = GinUserFieldsSchema{} }
func (m *GinUserFieldsSchema) String() string { return proto.CompactTextString(m) }
func (*GinUserFieldsSchema) ProtoMessage()    {}
func (*GinUserFieldsSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_02d571b60e8ca194, []int{0}
}

func (m *GinUserFieldsSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GinUserFieldsSchema.Unmarshal(m, b)
}
func (m *GinUserFieldsSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GinUserFieldsSchema.Marshal(b, m, deterministic)
}
func (m *GinUserFieldsSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GinUserFieldsSchema.Merge(m, src)
}
func (m *GinUserFieldsSchema) XXX_Size() int {
	return xxx_messageInfo_GinUserFieldsSchema.Size(m)
}
func (m *GinUserFieldsSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_GinUserFieldsSchema.DiscardUnknown(m)
}

var xxx_messageInfo_GinUserFieldsSchema proto.InternalMessageInfo

func (m *GinUserFieldsSchema) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GinUserFieldsSchema) GetSexy() string {
	if m != nil {
		return m.Sexy
	}
	return ""
}

func (m *GinUserFieldsSchema) GetBirthdy() string {
	if m != nil {
		return m.Birthdy
	}
	return ""
}

func (m *GinUserFieldsSchema) GetIdCard() string {
	if m != nil {
		return m.IdCard
	}
	return ""
}

func (m *GinUserFieldsSchema) GetTruthName() string {
	if m != nil {
		return m.TruthName
	}
	return ""
}

func (m *GinUserFieldsSchema) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *GinUserFieldsSchema) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

//更新结构
type UpdateSchema struct {
	Conditions           *GinUserFieldsSchema `protobuf:"bytes,1,opt,name=conditions,proto3" json:"conditions,omitempty"`
	Modifies             *GinUserFieldsSchema `protobuf:"bytes,2,opt,name=modifies,proto3" json:"modifies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateSchema) Reset()         { *m = UpdateSchema{} }
func (m *UpdateSchema) String() string { return proto.CompactTextString(m) }
func (*UpdateSchema) ProtoMessage()    {}
func (*UpdateSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_02d571b60e8ca194, []int{1}
}

func (m *UpdateSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSchema.Unmarshal(m, b)
}
func (m *UpdateSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSchema.Marshal(b, m, deterministic)
}
func (m *UpdateSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSchema.Merge(m, src)
}
func (m *UpdateSchema) XXX_Size() int {
	return xxx_messageInfo_UpdateSchema.Size(m)
}
func (m *UpdateSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSchema.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSchema proto.InternalMessageInfo

func (m *UpdateSchema) GetConditions() *GinUserFieldsSchema {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func (m *UpdateSchema) GetModifies() *GinUserFieldsSchema {
	if m != nil {
		return m.Modifies
	}
	return nil
}

//查询结构
type QuerySchema struct {
	Conditions           *GinUserFieldsSchema `protobuf:"bytes,1,opt,name=conditions,proto3" json:"conditions,omitempty"`
	PageNum              int32                `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize             int32                `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *QuerySchema) Reset()         { *m = QuerySchema{} }
func (m *QuerySchema) String() string { return proto.CompactTextString(m) }
func (*QuerySchema) ProtoMessage()    {}
func (*QuerySchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_02d571b60e8ca194, []int{2}
}

func (m *QuerySchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuerySchema.Unmarshal(m, b)
}
func (m *QuerySchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuerySchema.Marshal(b, m, deterministic)
}
func (m *QuerySchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySchema.Merge(m, src)
}
func (m *QuerySchema) XXX_Size() int {
	return xxx_messageInfo_QuerySchema.Size(m)
}
func (m *QuerySchema) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySchema.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySchema proto.InternalMessageInfo

func (m *QuerySchema) GetConditions() *GinUserFieldsSchema {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func (m *QuerySchema) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *QuerySchema) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

//查询返回对象
type FindOneRes struct {
	Code                 int32                `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string               `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *GinUserFieldsSchema `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FindOneRes) Reset()         { *m = FindOneRes{} }
func (m *FindOneRes) String() string { return proto.CompactTextString(m) }
func (*FindOneRes) ProtoMessage()    {}
func (*FindOneRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_02d571b60e8ca194, []int{3}
}

func (m *FindOneRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindOneRes.Unmarshal(m, b)
}
func (m *FindOneRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindOneRes.Marshal(b, m, deterministic)
}
func (m *FindOneRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindOneRes.Merge(m, src)
}
func (m *FindOneRes) XXX_Size() int {
	return xxx_messageInfo_FindOneRes.Size(m)
}
func (m *FindOneRes) XXX_DiscardUnknown() {
	xxx_messageInfo_FindOneRes.DiscardUnknown(m)
}

var xxx_messageInfo_FindOneRes proto.InternalMessageInfo

func (m *FindOneRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *FindOneRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *FindOneRes) GetData() *GinUserFieldsSchema {
	if m != nil {
		return m.Data
	}
	return nil
}

//查询返回string
type FindRes struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindRes) Reset()         { *m = FindRes{} }
func (m *FindRes) String() string { return proto.CompactTextString(m) }
func (*FindRes) ProtoMessage()    {}
func (*FindRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_02d571b60e8ca194, []int{4}
}

func (m *FindRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRes.Unmarshal(m, b)
}
func (m *FindRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRes.Marshal(b, m, deterministic)
}
func (m *FindRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRes.Merge(m, src)
}
func (m *FindRes) XXX_Size() int {
	return xxx_messageInfo_FindRes.Size(m)
}
func (m *FindRes) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRes.DiscardUnknown(m)
}

var xxx_messageInfo_FindRes proto.InternalMessageInfo

func (m *FindRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *FindRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *FindRes) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*GinUserFieldsSchema)(nil), "gin_user_fields_proto.GinUserFieldsSchema")
	proto.RegisterType((*UpdateSchema)(nil), "gin_user_fields_proto.UpdateSchema")
	proto.RegisterType((*QuerySchema)(nil), "gin_user_fields_proto.QuerySchema")
	proto.RegisterType((*FindOneRes)(nil), "gin_user_fields_proto.FindOneRes")
	proto.RegisterType((*FindRes)(nil), "gin_user_fields_proto.FindRes")
}

func init() {
	proto.RegisterFile("gin_user_fields.proto", fileDescriptor_02d571b60e8ca194)
}

var fileDescriptor_02d571b60e8ca194 = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xc1, 0xca, 0xd3, 0x40,
	0x10, 0x26, 0xff, 0xdf, 0x24, 0x7f, 0xa6, 0x0a, 0x65, 0x45, 0x8c, 0x15, 0xa5, 0xc6, 0x4b, 0xf1,
	0xd0, 0x43, 0xbd, 0x7b, 0xb0, 0x50, 0x41, 0xb0, 0xd5, 0x94, 0xaa, 0xb7, 0xb0, 0xcd, 0x4e, 0xd3,
	0x05, 0xb3, 0x29, 0xbb, 0x09, 0x98, 0xbe, 0x85, 0xaf, 0xe0, 0x9b, 0xf8, 0x38, 0xbe, 0x85, 0xec,
	0x24, 0x95, 0x28, 0xad, 0x5a, 0xd0, 0xdb, 0xcc, 0x7c, 0x33, 0xdf, 0x7c, 0x33, 0xb3, 0x0b, 0x77,
	0x33, 0xa9, 0x92, 0xca, 0xa0, 0x4e, 0xb6, 0x12, 0x3f, 0x0a, 0x33, 0xd9, 0xeb, 0xa2, 0x2c, 0xd8,
	0xaf, 0xe1, 0x84, 0xc2, 0xd1, 0x57, 0x07, 0xee, 0xbc, 0x94, 0x6a, 0x6d, 0x50, 0xcf, 0x29, 0xbe,
	0x4a, 0x77, 0x98, 0x73, 0x36, 0x80, 0xeb, 0x4a, 0x8a, 0xd0, 0x19, 0x39, 0x63, 0x37, 0xb6, 0x26,
	0x63, 0xd0, 0x33, 0xf8, 0xa9, 0x0e, 0xaf, 0x46, 0xce, 0x38, 0x88, 0xc9, 0x66, 0x21, 0xf8, 0x1b,
	0xa9, 0xcb, 0x9d, 0xa8, 0xc3, 0x6b, 0x0a, 0x1f, 0x5d, 0x76, 0x0f, 0x7c, 0x29, 0x92, 0x94, 0x6b,
	0x11, 0xf6, 0x08, 0xf1, 0xa4, 0x98, 0x71, 0x2d, 0xd8, 0x43, 0x80, 0x52, 0x57, 0xe5, 0x2e, 0x51,
	0x3c, 0xc7, 0xd0, 0x25, 0x2c, 0xa0, 0xc8, 0x82, 0xe7, 0x68, 0x19, 0x53, 0x8d, 0xbc, 0x44, 0x11,
	0x7a, 0x0d, 0x63, 0xeb, 0x5a, 0xa4, 0xda, 0x0b, 0x42, 0xfc, 0x06, 0x69, 0xdd, 0xe8, 0x8b, 0x03,
	0xb7, 0xd6, 0x64, 0xb7, 0xe2, 0x5f, 0x01, 0xa4, 0x85, 0x12, 0xb2, 0x94, 0x85, 0x32, 0x34, 0x43,
	0x7f, 0xfa, 0x74, 0x72, 0x72, 0x01, 0x93, 0x13, 0xc3, 0xc7, 0x9d, 0x6a, 0x36, 0x87, 0x9b, 0xbc,
	0x10, 0x72, 0x2b, 0xd1, 0xd0, 0xe8, 0x97, 0x31, 0xfd, 0xa8, 0x8d, 0x3e, 0x3b, 0xd0, 0x7f, 0x5b,
	0xa1, 0xae, 0xff, 0x83, 0xc6, 0xfb, 0x70, 0xb3, 0xe7, 0x19, 0x26, 0xaa, 0xca, 0x49, 0xa3, 0x1b,
	0xfb, 0xd6, 0x5f, 0x54, 0x39, 0x7b, 0x00, 0x01, 0x41, 0x46, 0x1e, 0x90, 0x6e, 0xe4, 0xc6, 0x94,
	0xbb, 0x92, 0x07, 0x8c, 0x34, 0xc0, 0x5c, 0x2a, 0xb1, 0x54, 0x18, 0xa3, 0xb1, 0x07, 0x4e, 0x0b,
	0x81, 0xed, 0xcd, 0xc9, 0xb6, 0xcf, 0x20, 0x37, 0x59, 0x7b, 0x73, 0x6b, 0xb2, 0xe7, 0xd0, 0x13,
	0xbc, 0xe4, 0xc4, 0x75, 0x99, 0x62, 0xaa, 0x8b, 0x66, 0xe0, 0xdb, 0x9e, 0x7f, 0xdf, 0x90, 0x75,
	0x1a, 0x06, 0x0d, 0xc9, 0xf4, 0xdb, 0x15, 0xdc, 0xfe, 0xa9, 0x05, 0x7b, 0x07, 0x03, 0x4b, 0xfb,
	0xa2, 0x7e, 0xc3, 0x33, 0xa9, 0xb8, 0xdd, 0x0b, 0x8b, 0xce, 0x88, 0xeb, 0x9c, 0x61, 0xf8, 0xe8,
	0x4c, 0xce, 0x51, 0xe3, 0x87, 0x46, 0xee, 0x52, 0x21, 0xbb, 0x60, 0xd6, 0xe1, 0xe3, 0xdf, 0xd0,
	0xb6, 0xeb, 0x7e, 0x0f, 0xde, 0x8c, 0x9e, 0xf6, 0xbf, 0x26, 0x7e, 0x0d, 0x5e, 0xf3, 0x1b, 0xd8,
	0x93, 0x33, 0xc9, 0xdd, 0xcf, 0xf2, 0xa7, 0x0d, 0x6c, 0x3c, 0x72, 0x9f, 0x7d, 0x0f, 0x00, 0x00,
	0xff, 0xff, 0x64, 0x2f, 0xca, 0x90, 0x58, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GinUserFieldsClient is the client API for GinUserFields service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GinUserFieldsClient interface {
	FindByPagination(ctx context.Context, in *QuerySchema, opts ...grpc.CallOption) (*FindRes, error)
	FindOne(ctx context.Context, in *GinUserFieldsSchema, opts ...grpc.CallOption) (*FindOneRes, error)
	Create(ctx context.Context, in *GinUserFieldsSchema, opts ...grpc.CallOption) (*FindOneRes, error)
	Update(ctx context.Context, in *UpdateSchema, opts ...grpc.CallOption) (*FindRes, error)
}

type ginUserFieldsClient struct {
	cc grpc.ClientConnInterface
}

func NewGinUserFieldsClient(cc grpc.ClientConnInterface) GinUserFieldsClient {
	return &ginUserFieldsClient{cc}
}

func (c *ginUserFieldsClient) FindByPagination(ctx context.Context, in *QuerySchema, opts ...grpc.CallOption) (*FindRes, error) {
	out := new(FindRes)
	err := c.cc.Invoke(ctx, "/gin_user_fields_proto.GinUserFields/FindByPagination", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ginUserFieldsClient) FindOne(ctx context.Context, in *GinUserFieldsSchema, opts ...grpc.CallOption) (*FindOneRes, error) {
	out := new(FindOneRes)
	err := c.cc.Invoke(ctx, "/gin_user_fields_proto.GinUserFields/FindOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ginUserFieldsClient) Create(ctx context.Context, in *GinUserFieldsSchema, opts ...grpc.CallOption) (*FindOneRes, error) {
	out := new(FindOneRes)
	err := c.cc.Invoke(ctx, "/gin_user_fields_proto.GinUserFields/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ginUserFieldsClient) Update(ctx context.Context, in *UpdateSchema, opts ...grpc.CallOption) (*FindRes, error) {
	out := new(FindRes)
	err := c.cc.Invoke(ctx, "/gin_user_fields_proto.GinUserFields/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GinUserFieldsServer is the server API for GinUserFields service.
type GinUserFieldsServer interface {
	FindByPagination(context.Context, *QuerySchema) (*FindRes, error)
	FindOne(context.Context, *GinUserFieldsSchema) (*FindOneRes, error)
	Create(context.Context, *GinUserFieldsSchema) (*FindOneRes, error)
	Update(context.Context, *UpdateSchema) (*FindRes, error)
}

// UnimplementedGinUserFieldsServer can be embedded to have forward compatible implementations.
type UnimplementedGinUserFieldsServer struct {
}

func (*UnimplementedGinUserFieldsServer) FindByPagination(ctx context.Context, req *QuerySchema) (*FindRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByPagination not implemented")
}
func (*UnimplementedGinUserFieldsServer) FindOne(ctx context.Context, req *GinUserFieldsSchema) (*FindOneRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOne not implemented")
}
func (*UnimplementedGinUserFieldsServer) Create(ctx context.Context, req *GinUserFieldsSchema) (*FindOneRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedGinUserFieldsServer) Update(ctx context.Context, req *UpdateSchema) (*FindRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}

func RegisterGinUserFieldsServer(s *grpc.Server, srv GinUserFieldsServer) {
	s.RegisterService(&_GinUserFields_serviceDesc, srv)
}

func _GinUserFields_FindByPagination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySchema)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GinUserFieldsServer).FindByPagination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gin_user_fields_proto.GinUserFields/FindByPagination",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GinUserFieldsServer).FindByPagination(ctx, req.(*QuerySchema))
	}
	return interceptor(ctx, in, info, handler)
}

func _GinUserFields_FindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GinUserFieldsSchema)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GinUserFieldsServer).FindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gin_user_fields_proto.GinUserFields/FindOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GinUserFieldsServer).FindOne(ctx, req.(*GinUserFieldsSchema))
	}
	return interceptor(ctx, in, info, handler)
}

func _GinUserFields_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GinUserFieldsSchema)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GinUserFieldsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gin_user_fields_proto.GinUserFields/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GinUserFieldsServer).Create(ctx, req.(*GinUserFieldsSchema))
	}
	return interceptor(ctx, in, info, handler)
}

func _GinUserFields_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSchema)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GinUserFieldsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gin_user_fields_proto.GinUserFields/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GinUserFieldsServer).Update(ctx, req.(*UpdateSchema))
	}
	return interceptor(ctx, in, info, handler)
}

var _GinUserFields_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gin_user_fields_proto.GinUserFields",
	HandlerType: (*GinUserFieldsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindByPagination",
			Handler:    _GinUserFields_FindByPagination_Handler,
		},
		{
			MethodName: "FindOne",
			Handler:    _GinUserFields_FindOne_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _GinUserFields_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _GinUserFields_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gin_user_fields.proto",
}
